// src/components/AdvancedTable.tsx
import React, { useState, useRef, useEffect } from 'react';
import { cn } from '@/lib/utils';
import { TableProps, TableColumn, SortState } from '@/lib/table-types';
import { CaretDown, CaretUp, CaretLeft, CaretRight, Plus, Minus } from '@phosphor-icons/react';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Skeleton } from '@/components/ui/skeleton';
import { Card } from '@/components/ui/card';

export function AdvancedTable<T extends Record<string, any>>({
  data,
  columns,
  loading = false,
  rowKey = 'id',
  expandable,
  pagination,
  sticky,
  scroll,
  onPageChange,
  onSort,
  onExpand,
  className
}: TableProps<T>) {
  const [sortState, setSortState] = useState<SortState>({ field: null, direction: null });
  const [expandedRows, setExpandedRows] = useState<Set<string>>(new Set());
  const tableRef = useRef<HTMLDivElement>(null);
  const headerRef = useRef<HTMLTableSectionElement>(null);

  const leftFrozenColumns = columns.filter(col => col.frozen === true || col.frozen === 'left');
  const rightFrozenColumns = columns.filter(col => col.frozen === 'right');
  const scrollableColumns = columns.filter(col => !col.frozen);

  const getRowKey = (record: T, index: number): string => {
    return typeof rowKey === 'function' ? rowKey(record) : String(record[rowKey] || index);
  };

  const handleSort = (column: TableColumn<T>) => {
    if (!column.sortable) return;

    let newDirection: 'asc' | 'desc' | null = 'asc';
    
    if (sortState.field === column.key) {
      if (sortState.direction === 'asc') {
        newDirection = 'desc';
      } else if (sortState.direction === 'desc') {
        newDirection = null;
      }
    }

    setSortState({ field: newDirection ? column.key : null, direction: newDirection });
    onSort?.(column.key, newDirection);
  };

  const handleExpand = (record: T) => {
    const key = getRowKey(record, 0);
    const newExpandedRows = new Set(expandedRows);
    
    if (newExpandedRows.has(key)) {
      newExpandedRows.delete(key);
      onExpand?.(false, record);
    } else {
      newExpandedRows.add(key);
      onExpand?.(true, record);
    }
    
    setExpandedRows(newExpandedRows);
  };

  const renderColumnHeader = (column: TableColumn<T>) => {
    const isLeftFrozen = column.frozen === true || column.frozen === 'left';
    const isRightFrozen = column.frozen === 'right';
    
    // Calculate left offset for left frozen columns
    let leftOffset = 0;
    if (isLeftFrozen) {
      if (expandable) leftOffset += 48; // Expand button width
      
      // Add widths of previous left frozen columns
      for (const leftCol of leftFrozenColumns) {
        if (leftCol.key === column.key) break;
        const width = leftCol.width;
        leftOffset += typeof width === 'number' ? width : parseInt(String(width) || '100');
      }
    }
    
    return (
      <th
        key={column.key}
        className={cn(
          "px-4 py-3 text-left text-sm font-medium text-foreground bg-card/95 backdrop-blur-sm border-b border-border",
          column.sortable && "cursor-pointer hover:bg-muted/50 transition-colors",
          isLeftFrozen && "sticky z-30 bg-card/95 backdrop-blur-sm",
          isRightFrozen && "sticky right-0 z-30 bg-card/95 backdrop-blur-sm"
        )}
        style={{
          width: column.width,
          minWidth: column.minWidth,
          maxWidth: column.maxWidth,
          ...(isLeftFrozen && { left: leftOffset }),
        }}
        onClick={() => handleSort(column)}
      >
        <div className="flex items-center gap-2">
          <span className={cn(column.ellipsis && "truncate")}>{column.title}</span>
          {column.sortable && (
            <div className="flex flex-col">
              {sortState.field === column.key ? (
                sortState.direction === 'asc' ? (
                  <CaretUp size={14} className="text-primary" />
                ) : sortState.direction === 'desc' ? (
                  <CaretDown size={14} className="text-primary" />
                ) : (
                  <div className="flex flex-col">
                    <CaretUp size={12} className="text-muted-foreground" />
                    <CaretDown size={12} className="text-muted-foreground -mt-1" />
                  </div>
                )
              ) : (
                <div className="flex flex-col">
                  <CaretUp size={12} className="text-muted-foreground" />
                  <CaretDown size={12} className="text-muted-foreground -mt-1" />
                </div>
              )}
            </div>
          )}
        </div>
      </th>
    );
  };

  const renderCell = (column: TableColumn<T>, record: T, index: number) => {
    const value = record[column.key];
    const content = column.render ? column.render(value, record, index) : value;
    const isLeftFrozen = column.frozen === true || column.frozen === 'left';
    const isRightFrozen = column.frozen === 'right';
    
    // Calculate left offset for left frozen columns
    let leftOffset = 0;
    if (isLeftFrozen) {
      if (expandable) leftOffset += 48; // Expand button width
      
      // Add widths of previous left frozen columns
      for (const leftCol of leftFrozenColumns) {
        if (leftCol.key === column.key) break;
        const width = leftCol.width;
        leftOffset += typeof width === 'number' ? width : parseInt(String(width) || '100');
      }
    }
    
    return (
      <td
        key={column.key}
        className={cn(
          "px-4 py-3 text-sm border-b border-border",
          isLeftFrozen && "sticky z-10 bg-card",
          isRightFrozen && "sticky right-0 z-10 bg-card",
          column.ellipsis && "max-w-0",
          column.multiline ? "whitespace-normal" : "whitespace-nowrap"
        )}
        style={{
          width: column.width,
          minWidth: column.minWidth,
          maxWidth: column.maxWidth,
          ...(isLeftFrozen && { left: leftOffset }),
        }}
      >
        {column.ellipsis ? (
          <div className="truncate" title={String(value)}>
            {content}
          </div>
        ) : (
          content
        )}
      </td>
    );
  };

  const renderExpandButton = (record: T, index: number) => {
    const key = getRowKey(record, index);
    const isExpanded = expandedRows.has(key);

    return (
      <td className="px-4 py-3 border-b border-border">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => handleExpand(record)}
          className="h-6 w-6 p-0"
        >
          {isExpanded ? <Minus size={14} /> : <Plus size={14} />}
        </Button>
      </td>
    );
  };

  const renderPagination = () => {
    if (!pagination || !pagination.showPagination) return null;

    const { current, pageSize, total, showSizeChanger, pageSizeOptions = [10, 20, 50, 100] } = pagination;
    const totalPages = Math.ceil(total / pageSize);
    const startItem = (current - 1) * pageSize + 1;
    const endItem = Math.min(current * pageSize, total);

    return (
      <div className="flex items-center justify-between px-4 py-3 border-t border-border bg-card">
        <div className="flex items-center gap-4">
          <span className="text-sm text-muted-foreground">
            Showing {startItem} to {endItem} of {total} results
          </span>
          {showSizeChanger && (
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground">Show</span>
              <Select
                value={pageSize.toString()}
                onValueChange={(value) => onPageChange?.(1, parseInt(value))}
              >
                <SelectTrigger className="w-20">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {pageSizeOptions.map(size => (
                    <SelectItem key={size} value={size.toString()}>
                      {size}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}
        </div>
        
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => onPageChange?.(current - 1, pageSize)}
            disabled={current <= 1}
          >
            <CaretLeft size={16} />
          </Button>
          
          <span className="text-sm text-muted-foreground">
            Page {current} of {totalPages}
          </span>
          
          <Button
            variant="outline"
            size="sm"
            onClick={() => onPageChange?.(current + 1, pageSize)}
            disabled={current >= totalPages}
          >
            <CaretRight size={16} />
          </Button>
        </div>
      </div>
    );
  };

  if (loading) {
    return (
      <Card className={cn("overflow-hidden", className)}>
        <div className="p-4">
          <Skeleton className="h-8 w-full mb-4" />
          {Array.from({ length: 5 }).map((_, i) => (
            <Skeleton key={i} className="h-12 w-full mb-2" />
          ))}
        </div>
      </Card>
    );
  }

  return (
    <Card className={cn("overflow-hidden", className)}>
      <div
        ref={tableRef}
        className="overflow-auto"
        style={{ 
          maxHeight: scroll?.y || undefined
        }}
      >
        <table className="w-full table-fixed" style={{ minWidth: scroll?.x }}>
          <thead ref={headerRef} className="bg-card/95 backdrop-blur-sm sticky top-0 z-20 shadow-sm">
            <tr>
              {expandable && (
                <th className="w-12 px-4 py-3 bg-card/95 backdrop-blur-sm border-b border-border sticky left-0 z-30" />
              )}
              {leftFrozenColumns.map(renderColumnHeader)}
              {scrollableColumns.map(renderColumnHeader)}
              {rightFrozenColumns.map(renderColumnHeader)}
            </tr>
          </thead>
          <tbody>
            {data.length === 0 ? (
              <tr>
                <td
                  colSpan={columns.length + (expandable ? 1 : 0)}
                  className="px-4 py-8 text-center text-muted-foreground"
                >
                  No data available
                </td>
              </tr>
            ) : (
              data.map((record, index) => {
                const key = getRowKey(record, index);
                const isExpanded = expandedRows.has(key);
                
                return (
                  <React.Fragment key={key}>
                    <tr
                      className={cn(
                        "hover:bg-muted/50 transition-colors",
                        expandable?.expandRowByClick && "cursor-pointer"
                      )}
                      onClick={() => expandable?.expandRowByClick && handleExpand(record)}
                    >
                      {expandable && !expandable.expandRowByClick && renderExpandButton(record, index)}
                      {leftFrozenColumns.map(column => renderCell(column, record, index))}
                      {scrollableColumns.map(column => renderCell(column, record, index))}
                      {rightFrozenColumns.map(column => renderCell(column, record, index))}
                    </tr>
                    {expandable && isExpanded && (
                      <tr>
                        <td colSpan={columns.length + 1} className="p-0 border-b border-border">
                          <div className="p-4 bg-muted/20">
                            {expandable.expandedRowRender(record, index)}
                          </div>
                        </td>
                      </tr>
                    )}
                  </React.Fragment>
                );
              })
            )}
          </tbody>
        </table>
      </div>
      {renderPagination()}
    </Card>
  );
}

// angular/src/app/components/advanced-table.component.ts
import { Component, input, output, OnInit, OnChanges, OnDestroy, SimpleChanges, ElementRef, ViewChild, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ButtonComponent } from './ui/button.component';
import { TableColumn, TableProps, SortState } from '../types/table.types';

@Component({
  selector: 'app-advanced-table',
  standalone: true,
  imports: [CommonModule, FormsModule, ButtonComponent],
  templateUrl: './advanced-table.component.html',
  styleUrl: './advanced-table.component.css'
})
export class AdvancedTableComponent<T = any> implements OnInit, OnChanges, OnDestroy, AfterViewInit {
  data = input<T[]>([]);
  columns = input<TableColumn<T>[]>([]);
  loading = input<boolean>(false);
  rowKey = input<string | ((record: T) => string)>('id');
  expandable = input<TableProps<T>['expandable']>();
  pagination = input<TableProps<T>['pagination']>();
  sticky = input<TableProps<T>['sticky']>();
  scroll = input<TableProps<T>['scroll']>();
  className = input<string>('');

  pageChange = output<{page: number, pageSize: number}>();
  sort = output<{field: string | null, direction: 'asc' | 'desc' | null}>();
  expand = output<{expanded: boolean, record: T}>();

  @ViewChild('tableContainer', { static: false }) tableContainer!: ElementRef<HTMLDivElement>;
  @ViewChild('headerElement', { static: false }) headerElement!: ElementRef<HTMLTableSectionElement>;

  sortState: SortState = { field: null, direction: null };
  expandedRows = new Set<string>();
  currentPage = 1;
  currentPageSize = 10;
  stickyTop = 0;

  private scrollListener?: () => void;
  private resizeListener?: () => void;

  ngOnInit(): void {
    const pagination = this.pagination();
    if (pagination) {
      this.currentPage = pagination.current;
      this.currentPageSize = pagination.pageSize;
    }
  }

  ngAfterViewInit(): void {
    this.setupStickyPositioning();
  }

  ngOnChanges(changes: SimpleChanges): void {
    const pagination = this.pagination();
    if (changes['pagination'] && pagination) {
      this.currentPage = pagination.current;
      this.currentPageSize = pagination.pageSize;
    }
  }

  ngOnDestroy(): void {
    if (this.scrollListener) {
      window.removeEventListener('scroll', this.scrollListener);
    }
    if (this.resizeListener) {
      window.removeEventListener('resize', this.resizeListener);
    }
  }

  get leftFrozenColumns(): TableColumn<T>[] {
    return this.columns().filter(col => col.frozen === true || col.frozen === 'left');
  }

  get rightFrozenColumns(): TableColumn<T>[] {
    return this.columns().filter(col => col.frozen === 'right');
  }

  get scrollableColumns(): TableColumn<T>[] {
    return this.columns().filter(col => !col.frozen);
  }

  get totalPages(): number {
    const pagination = this.pagination();
    if (!pagination?.total) return 0;
    return Math.ceil(pagination.total / this.currentPageSize);
  }

  get startItem(): number {
    const pagination = this.pagination();
    if (!pagination?.total || pagination.total === 0) return 1;
    return (this.currentPage - 1) * this.currentPageSize + 1;
  }

  get endItem(): number {
    const pagination = this.pagination();
    const calculated = this.currentPage * this.currentPageSize;
    if (!pagination?.total) return this.paginatedData.length;
    
    return Math.min(calculated, pagination.total);
  }

  get flexibleColumns(): number {
    return this.columns().filter(col => !col.width).length;
  }

  get paginatedData(): T[] {
    const data = this.data();
    if (!data || data.length === 0) return [];
    
    const start = (this.currentPage - 1) * this.currentPageSize;
    const end = start + this.currentPageSize;
    
    return data.slice(start, end);
  }

  trackByColumn(index: number, column: TableColumn<T>): string {
    return column.key;
  }

  trackByRow(index: number, row: T): string {
    const rowKey = this.rowKey();
    return typeof rowKey === 'function' ? rowKey(row) : (row as any)[rowKey];
  }

  getTableClasses(): string {
    const baseClasses = 'w-full border-collapse table-fixed';
    const loadingClasses = this.loading() ? 'opacity-50 cursor-not-allowed' : '';
    return `${baseClasses} ${loadingClasses}`.trim();
  }

  getHeaderClasses(column: TableColumn<T>): string {
    const baseClasses = 'px-4 py-3 text-left border-b border-border';
    const frozenClasses = column.frozen ? 'sticky z-40 border-r-2 shadow-lg shadow-black/5 relative' : '';
    const stickyClasses = this.sticky() ? 'table-header-blur' : '';
    const sortableClasses = column.sortable ? 'cursor-pointer hover:bg-muted/50' : '';
    
    let positionClasses = '';
    if (column.frozen === true || column.frozen === 'left') {
      positionClasses = 'left-0';
    } else if (column.frozen === 'right') {
      positionClasses = 'right-0';
    }

    return `${baseClasses} ${frozenClasses} ${stickyClasses} ${sortableClasses} ${positionClasses}`.trim();
  }

  getCellClasses(column: TableColumn<T>): string {
    const baseClasses = 'px-4 py-3 border-b border-border transition-colors';
    const frozenClasses = column.frozen ? 'sticky z-30 border-r-2 shadow-lg shadow-black/5 relative' : '';
    const stickyClasses = this.sticky() ? 'table-cell-blur' : '';
    
    let positionClasses = '';
    if (column.frozen === true || column.frozen === 'left') {
      positionClasses = 'left-0';
    } else if (column.frozen === 'right') {
      positionClasses = 'right-0';
    }

    return `${baseClasses} ${frozenClasses} ${stickyClasses} ${positionClasses}`.trim();
  }

  getCellContentClasses(column: TableColumn<T>): string {
    return column.ellipsis ? 'truncate' : '';
  }

  getColumnStyle(column: TableColumn<T>): Record<string, string> {
    const style: Record<string, string> = {};
    
    if (column.width) {
      style['width'] = `${column.width}px`;
    }
    if (column.minWidth) {
      style['min-width'] = `${column.minWidth}px`;
    }
    if (column.maxWidth) {
      style['max-width'] = `${column.maxWidth}px`;
    }
    
    const sticky = this.sticky();
    if (sticky) {
      style['top'] = `${this.stickyTop}px`;
    }

    return style;
  }

  getCellStyle(column: TableColumn<T>): Record<string, string> {
    const style: Record<string, string> = {};
    
    if (column.width) {
      style['width'] = `${column.width}px`;
    }
    if (column.minWidth) {
      style['min-width'] = `${column.minWidth}px`;
    }
    if (column.maxWidth) {
      style['max-width'] = `${column.maxWidth}px`;
    }

    return style;
  }

  getLayoutColumnStyle(column: TableColumn<T>): Record<string, string> {
    return this.getColumnStyle(column);
  }

  handleSort(field: string): void {
    if (this.loading()) return;

    if (this.sortState.field === field) {
      // Cycle through: asc -> desc -> null
      if (this.sortState.direction === 'asc') {
        this.sortState.direction = 'desc';
      } else if (this.sortState.direction === 'desc') {
        this.sortState.field = null;
        this.sortState.direction = null;
      }
    } else {
      this.sortState.field = field;
      this.sortState.direction = 'asc';
    }

    this.sort.emit({
      field: this.sortState.field,
      direction: this.sortState.direction
    });
  }

  isExpanded(row: T): boolean {
    const rowKey = this.rowKey();
    const key = typeof rowKey === 'function' ? rowKey(row) : (row as any)[rowKey];
    return this.expandedRows.has(String(key));
  }

  toggleExpanded(row: T): void {
    const rowKey = this.rowKey();
    const key = typeof rowKey === 'function' ? rowKey(row) : (row as any)[rowKey];
    const keyStr = String(key);
    
    const wasExpanded = this.expandedRows.has(keyStr);
    
    if (wasExpanded) {
      this.expandedRows.delete(keyStr);
    } else {
      this.expandedRows.add(keyStr);
    }

    this.expand.emit({
      expanded: !wasExpanded,
      record: row
    });
  }

  getCellContent(row: T, column: TableColumn<T>, index: number): string {
    const value = (row as any)[column.key];
    
    if (column.render) {
      return column.render(value, row, index);
    }
    
    return value != null ? String(value) : '';
  }

  onPageChange(page: number): void {
    this.currentPage = page;
    this.pageChange.emit({
      page: this.currentPage,
      pageSize: this.currentPageSize
    });
  }

  onPageSizeChange(): void {
    this.currentPage = 1;
    this.pageChange.emit({
      page: this.currentPage,
      pageSize: this.currentPageSize
    });
  }

  onPrevPage(): void {
    if (this.currentPage > 1) {
      this.onPageChange(this.currentPage - 1);
    }
  }

  onNextPage(): void {
    if (this.currentPage < this.totalPages) {
      this.onPageChange(this.currentPage + 1);
    }
  }

  private setupStickyPositioning(): void {
    const updateStickyTop = () => {
      const sticky = this.sticky();
      if (sticky) {
        this.stickyTop = sticky.offsetHeader || 0;
      }
    };

    updateStickyTop();

    this.scrollListener = () => updateStickyTop();
    this.resizeListener = () => updateStickyTop();

    window.addEventListener('scroll', this.scrollListener);
    window.addEventListener('resize', this.resizeListener);
  }
}
<div [class]="'flex flex-col ' + (className() || '')">
  <div class="flex flex-col relative border rounded-lg bg-card">
    <!-- Loading overlay -->
    @if (loading()) {
      <div class="absolute inset-0 z-[100] flex items-center justify-center bg-card/90 backdrop-blur-md">
        <div class="bg-card/90 backdrop-blur-md rounded-lg px-6 py-4 shadow-lg border border-border">
          <div class="flex items-center gap-3">
            <div class="animate-spin h-5 w-5 border-2 border-primary border-t-transparent rounded-full"></div>
            <span class="text-sm font-medium text-foreground">Loading data...</span>
          </div>
        </div>
      </div>
    }

    <!-- Table container -->
    <div #tableContainer class="overflow-x-auto flex-1 scrollbar-visible" [style.max-height]="scroll()?.y">
      <table [class]="getTableClasses()" [style.min-width]="scroll()?.x">
        
        <!-- Table header -->
        <thead #headerElement 
               class="sticky z-40 border-b border-border"
               [class.table-header-blur]="sticky()"
               [style.top.px]="sticky() ? stickyTop : 0">
          <tr>
            <!-- Expand column header -->
            @if (expandable()) {
              <th class="w-12 px-4 py-3 sticky left-0 z-50 border-b border-border border-r-2 shadow-lg shadow-black/5 relative"
                  [class.table-header-blur]="sticky()"
                  [style.top.px]="sticky() ? stickyTop : 0">
                <span class="sr-only">Expand</span>
              </th>
            }
            
            <!-- Column headers -->
            @for (column of columns(); track trackByColumn($index, column)) {
              <th [class]="getHeaderClasses(column)"
                  [style]="getColumnStyle(column)"
                  (click)="!loading() && column.sortable ? handleSort(column.key) : null">
                <div class="flex items-center gap-2">
                  <span [class]="column.ellipsis ? 'truncate' : ''">{{ column.title }}</span>
                  @if (column.sortable) {
                    <div class="flex flex-col">
                      @if (sortState.field === column.key && sortState.direction === 'asc') {
                        <svg width="14" height="14" viewBox="0 0 256 256" class="text-primary">
                          <path fill="currentColor" d="m213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80a8,8,0,0,1,11.32-11.32L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z" transform="rotate(180 128 128)"/>
                        </svg>
                      }
                      @if (sortState.field === column.key && sortState.direction === 'desc') {
                        <svg width="14" height="14" viewBox="0 0 256 256" class="text-primary">
                          <path fill="currentColor" d="m213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80a8,8,0,0,1,11.32-11.32L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z"/>
                        </svg>
                      }
                      @if (!sortState.field || sortState.field !== column.key) {
                        <div class="flex flex-col">
                          <svg width="12" height="12" viewBox="0 0 256 256" class="text-muted-foreground">
                            <path fill="currentColor" d="m213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80a8,8,0,0,1,11.32-11.32L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z" transform="rotate(180 128 128)"/>
                          </svg>
                          <svg width="12" height="12" viewBox="0 0 256 256" class="text-muted-foreground -mt-1">
                            <path fill="currentColor" d="m213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80a8,8,0,0,1,11.32-11.32L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z"/>
                          </svg>
                        </div>
                      }
                    </div>
                  }
                </div>
              </th>
            }
          </tr>
        </thead>
        
        <!-- Table body -->
        <tbody>
          @if (data().length === 0) {
            <tr>
              <td [colSpan]="columns().length + (expandable() ? 1 : 0)"
                  class="py-8 text-center text-muted-foreground">
                No data available
              </td>
            </tr>
          } @else {
            @for (row of paginatedData; track trackByRow($index, row)) {
              <!-- Main row -->
              <tr class="table-row hover:bg-muted/50 transition-colors"
                  [class.cursor-pointer]="expandable()?.expandRowByClick"
                  (click)="expandable()?.expandRowByClick ? toggleExpanded(row) : null">
                
                <!-- Expand button -->
                @if (expandable()) {
                  <td class="px-4 py-3 sticky left-0 z-30 w-12 border-r-2 shadow-lg shadow-black/5 relative transition-colors"
                      [class.table-cell-blur]="sticky()">
                    @if (!expandable()?.expandRowByClick) {
                      <app-button variant="ghost" 
                                  size="sm" 
                                  class="h-6 w-6 p-0"
                                  (click)="toggleExpanded(row)">
                        @if (!isExpanded(row)) {
                          <svg width="14" height="14" viewBox="0 0 256 256">
                            <path fill="currentColor" d="M224,128a8,8,0,0,1-8,8H136v80a8,8,0,0,1-16,0V136H40a8,8,0,0,1,0-16h80V40a8,8,0,0,1,16,0v80h80A8,8,0,0,1,224,128Z"/>
                          </svg>
                        }
                        @if (isExpanded(row)) {
                          <svg width="14" height="14" viewBox="0 0 256 256">
                            <path fill="currentColor" d="M224,128a8,8,0,0,1-8,8H40a8,8,0,0,1,0-16H216A8,8,0,0,1,224,128Z"/>
                          </svg>
                        }
                      </app-button>
                    } @else {
                      <div class="flex items-center justify-center h-6 w-6">
                        @if (!isExpanded(row)) {
                          <svg width="14" height="14" viewBox="0 0 256 256" class="text-muted-foreground">
                            <path fill="currentColor" d="M224,128a8,8,0,0,1-8,8H136v80a8,8,0,0,1-16,0V136H40a8,8,0,0,1,0-16h80V40a8,8,0,0,1,16,0v80h80A8,8,0,0,1,224,128Z"/>
                          </svg>
                        }
                        @if (isExpanded(row)) {
                          <svg width="14" height="14" viewBox="0 0 256 256" class="text-muted-foreground">
                            <path fill="currentColor" d="M224,128a8,8,0,0,1-8,8H40a8,8,0,0,1,0-16H216A8,8,0,0,1,224,128Z"/>
                          </svg>
                        }
                      </div>
                    }
                  </td>
                }
                
                <!-- Data columns -->
                @for (column of columns(); track trackByColumn($index, column)) {
                  <td [class]="getCellClasses(column)"
                      [style]="getCellStyle(column)">
                    <div [class]="getCellContentClasses(column)"
                         [title]="column.ellipsis ? getCellContent(row, column, $index) : null"
                         [innerHTML]="getCellContent(row, column, $index)">
                    </div>
                  </td>
                }
              </tr>
              
              <!-- Expanded row -->
              @if (isExpanded(row)) {
                <tr class="expanded-row">
                  <td [colSpan]="columns().length + (expandable() ? 1 : 0)"
                      class="px-4 py-4 bg-muted/25">
                    <div [innerHTML]="expandable()?.expandedRowRender?.(row, $index) || ''"></div>
                  </td>
                </tr>
              }
            }
          }
        </tbody>
      </table>
    </div>

    <!-- Pagination -->
    @if (pagination()?.showPagination !== false) {
      <div class="flex items-center justify-between px-4 py-3 border-t border-border bg-card">
        <div class="flex items-center gap-4">
          <span class="text-sm text-muted-foreground">
            Showing {{ startItem }} to {{ endItem }} of {{ pagination()?.total || 0 }} results
          </span>
          @if (pagination()?.showSizeChanger) {
            <div class="flex items-center gap-2">
              <span class="text-sm text-muted-foreground">Show</span>
              <select [(ngModel)]="currentPageSize" 
                      (change)="onPageSizeChange()" 
                      class="w-20 h-8 rounded-md border border-input bg-background px-3 py-1 text-sm">
                @for (size of pagination()?.pageSizeOptions || [10, 20, 50]; track size) {
                  <option [value]="size">{{ size }}</option>
                }
              </select>
            </div>
          }
        </div>
        
        <div class="flex items-center gap-2">
          <app-button variant="outline" size="sm" [disabled]="currentPage <= 1" (click)="onPrevPage()">
            <svg width="16" height="16" viewBox="0 0 256 256">
              <path fill="currentColor" d="m221.66,133.66l-80,80a8,8,0,0,1-11.32-11.32L204.69,128,130.34,53.66a8,8,0,0,1,11.32-11.32l80,80A8,8,0,0,1,221.66,133.66Z" transform="rotate(180 128 128)"/>
            </svg>
          </app-button>
          
          <span class="text-sm text-muted-foreground">
            Page {{ currentPage }} of {{ totalPages }}
          </span>
          
          <app-button variant="outline" size="sm" [disabled]="currentPage >= totalPages" (click)="onNextPage()">
            <svg width="16" height="16" viewBox="0 0 256 256">
              <path fill="currentColor" d="m221.66,133.66l-80,80a8,8,0,0,1-11.32-11.32L204.69,128,130.34,53.66a8,8,0,0,1,11.32-11.32l80,80A8,8,0,0,1,221.66,133.66Z"/>
            </svg>
          </app-button>
        </div>
      </div>
    }
  </div>
</div>
