// src/components/TableDemo.tsx
import React, { useState, useEffect } from 'react';
import { AdvancedTable } from '@/components/AdvancedTable';
import { TableColumn } from '@/lib/table-types';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { ThemeSwitcher } from '@/components/ThemeSwitcher';

interface User {
  id: string;
  name: string;
  email: string;
  role: string;
  status: 'active' | 'inactive' | 'pending';
  joinDate: string;
  lastLogin: string;
  department: string;
  salary: number;
  description: string;
}

const generateSampleData = (): User[] => {
  const names = ['John Doe', 'Jane Smith', 'Mike Johnson', 'Sarah Wilson', 'David Brown', 'Emma Davis', 'Tom Wilson', 'Lisa Anderson', 'Chris Taylor', 'Anna Miller'];
  const roles = ['Admin', 'User', 'Manager', 'Developer', 'Designer', 'Analyst'];
  const departments = ['Engineering', 'Marketing', 'Sales', 'HR', 'Finance', 'Operations'];
  const statuses: ('active' | 'inactive' | 'pending')[] = ['active', 'inactive', 'pending'];

  return Array.from({ length: 50 }, (_, i) => ({
    id: `user-${i + 1}`,
    name: names[i % names.length] + ` ${i + 1}`,
    email: `user${i + 1}@company.com`,
    role: roles[i % roles.length],
    status: statuses[i % statuses.length],
    joinDate: new Date(2020 + (i % 4), (i % 12), (i % 28) + 1).toISOString().split('T')[0],
    lastLogin: new Date(2024, 0, (i % 30) + 1).toISOString().split('T')[0],
    department: departments[i % departments.length],
    salary: 50000 + (i * 1000),
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. User ${i + 1} details.`
  }));
};

export function TableDemo() {
  const [data, setData] = useState<User[]>([]);
  const [loading, setLoading] = useState(true);
  const [pagination, setPagination] = useState({
    current: 1,
    pageSize: 10,
    total: 0
  });
  const [sortState, setSortState] = useState<{
    field: string | null;
    direction: 'asc' | 'desc' | null;
  }>({
    field: null,
    direction: null
  });

  const allData = generateSampleData();

  useEffect(() => {
    // Simulate loading
    setLoading(true);
    setTimeout(() => {
      let filteredData = [...allData];
      
      // Apply sorting
      if (sortState.field && sortState.direction) {
        filteredData.sort((a, b) => {
          const aVal = a[sortState.field as keyof User];
          const bVal = b[sortState.field as keyof User];
          
          let comparison = 0;
          if (aVal < bVal) comparison = -1;
          if (aVal > bVal) comparison = 1;
          
          return sortState.direction === 'desc' ? -comparison : comparison;
        });
      }

      // Apply pagination
      const startIndex = (pagination.current - 1) * pagination.pageSize;
      const endIndex = startIndex + pagination.pageSize;
      const paginatedData = filteredData.slice(startIndex, endIndex);

      setData(paginatedData);
      setPagination(prev => ({ ...prev, total: filteredData.length }));
      setLoading(false);
    }, 500);
  }, [pagination.current, pagination.pageSize, sortState]);

  const columns: TableColumn<User>[] = [
    {
      key: 'id',
      title: 'ID',
      width: 100,
      frozen: true,
      sortable: true,
      ellipsis: true,
    },
    {
      key: 'name',
      title: 'Name',
      width: 200,
      frozen: true,
      sortable: true,
      render: (value, record) => (
        <div className="font-medium text-foreground">{value}</div>
      ),
    },
    {
      key: 'email',
      title: 'Email',
      // No width specified - will take available space
      sortable: true,
      ellipsis: true,
    },
    {
      key: 'role',
      title: 'Role',
      width: 120,
      sortable: true,
      render: (value) => (
        <Badge variant="secondary">{value}</Badge>
      ),
    },
    {
      key: 'status',
      title: 'Status',
      width: 120,
      sortable: true,
      render: (value) => (
        <Badge 
          variant={value === 'active' ? 'default' : value === 'pending' ? 'secondary' : 'destructive'}
        >
          {value}
        </Badge>
      ),
    },
    {
      key: 'department',
      title: 'Department',
      // No width specified - will take available space
      sortable: true,
    },
    {
      key: 'joinDate',
      title: 'Join Date',
      width: 120,
      sortable: true,
    },
    {
      key: 'lastLogin',
      title: 'Last Login',
      width: 120,
      sortable: true,
      frozen: 'right',
    },
    {
      key: 'salary',
      title: 'Salary',
      width: 120,
      sortable: true,
      render: (value) => `$${value.toLocaleString()}`,
    },
    {
      key: 'description',
      title: 'Description',
      // No width specified - will take available space
      ellipsis: true,
      multiline: false,
    },
  ];

  const handlePageChange = (page: number, pageSize: number) => {
    setPagination(prev => ({ ...prev, current: page, pageSize }));
  };

  const handleSort = (field: string, direction: 'asc' | 'desc' | null) => {
    setSortState({ field, direction });
    setPagination(prev => ({ ...prev, current: 1 })); // Reset to first page
  };

  const expandedRowRender = (record: User) => (
    <div className="space-y-4">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <Card className="p-4">
          <h4 className="font-semibold mb-2">Contact Information</h4>
          <div className="space-y-1 text-sm">
            <div><span className="font-medium">Email:</span> {record.email}</div>
            <div><span className="font-medium">Department:</span> {record.department}</div>
            <div><span className="font-medium">Role:</span> {record.role}</div>
          </div>
        </Card>
        
        <Card className="p-4">
          <h4 className="font-semibold mb-2">Employment Details</h4>
          <div className="space-y-1 text-sm">
            <div><span className="font-medium">Join Date:</span> {record.joinDate}</div>
            <div><span className="font-medium">Last Login:</span> {record.lastLogin}</div>
            <div><span className="font-medium">Salary:</span> ${record.salary.toLocaleString()}</div>
          </div>
        </Card>
        
        <Card className="p-4">
          <h4 className="font-semibold mb-2">Description</h4>
          <p className="text-sm text-muted-foreground">{record.description}</p>
        </Card>
      </div>
      
      <div className="flex gap-2">
        <Button size="sm" variant="outline">Edit User</Button>
        <Button size="sm" variant="outline">View Profile</Button>
        <Button size="sm" variant="destructive">Delete User</Button>
      </div>
    </div>
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="space-y-2">
          <h1 className="text-2xl font-semibold">Advanced Data Table</h1>
          <p className="text-muted-foreground">
            A comprehensive table component with sticky headers, sorting, pagination, expandable rows, frozen columns, and flexible width handling.
          </p>
        </div>
        <ThemeSwitcher />
      </div>

      <div>
        <AdvancedTable
          data={data}
          columns={columns}
          loading={loading}
          rowKey="id"
          expandable={{
            expandedRowRender,
            expandRowByClick: false,
          }}
          pagination={{
            current: pagination.current,
            pageSize: pagination.pageSize,
            total: pagination.total,
            showSizeChanger: true,
            pageSizeOptions: [5, 10, 20, 50],
            showPagination: true,
          }}
          sticky={{
            offsetHeader: 0,
          }}
          scroll={{
            x: 1200, // Reduced since some columns are now flexible
          }}
          onPageChange={handlePageChange}
          onSort={handleSort}
          onExpand={(expanded, record) => {
            console.log('Row expanded:', expanded, record);
          }}
          className="shadow-sm"
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="p-4">
          <h3 className="font-semibold mb-2">Features Demonstrated</h3>
          <ul className="text-sm space-y-1 text-muted-foreground">
            <li>• Sticky header behavior</li>
            <li>• Frozen columns (ID & Name)</li>
            <li>• Sortable columns</li>
            <li>• Expandable rows</li>
          </ul>
        </Card>
        
        <Card className="p-4">
          <h3 className="font-semibold mb-2">Pagination</h3>
          <ul className="text-sm space-y-1 text-muted-foreground">
            <li>• Configurable page sizes</li>
            <li>• Page navigation</li>
            <li>• Total count display</li>
            <li>• Persistent state</li>
          </ul>
        </Card>
        
        <Card className="p-4">
          <h3 className="font-semibold mb-2">Column Features</h3>
          <ul className="text-sm space-y-1 text-muted-foreground">
            <li>• Fixed & flexible widths</li>
            <li>• Text ellipsis handling</li>
            <li>• Custom cell rendering</li>
            <li>• Horizontal scrolling</li>
          </ul>
        </Card>
        
        <Card className="p-4">
          <h3 className="font-semibold mb-2">Event Driven</h3>
          <ul className="text-sm space-y-1 text-muted-foreground">
            <li>• Sort events</li>
            <li>• Pagination events</li>
            <li>• Expand events</li>
            <li>• Loading states</li>
          </ul>
        </Card>
      </div>

      {/* Add extra content to enable scrolling and test sticky header */}
      <div className="space-y-4">
        <h2 className="text-xl font-semibold">Additional Content for Scroll Testing</h2>
        <p className="text-muted-foreground">
          Scroll down to see the sticky header behavior in action. The table header should remain visible at the top of the viewport.
        </p>
        
        {Array.from({ length: 20 }).map((_, i) => (
          <Card key={i} className="p-6">
            <h3 className="font-semibold mb-2">Section {i + 1}</h3>
            <p className="text-muted-foreground mb-4">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor 
              incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 
              exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </p>
            <p className="text-muted-foreground">
              Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu 
              fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in 
              culpa qui officia deserunt mollit anim id est laborum.
            </p>
          </Card>
        ))}
      </div>
    </div>
  );
}

// angular/src/app/components/table-demo/table-demo.component.ts
import { Component, OnInit, TemplateRef, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AdvancedTableComponent } from '../advanced-table/advanced-table.component';
import { BadgeComponent } from '../ui/badge/badge.component';
import { ButtonComponent } from '../ui/button/button.component';
import { TableColumn } from '../../types/table-types';
import { User } from '../../types/user.interface';
import { UserDataService } from '../../services/user-data.service';

@Component({
  selector: 'app-table-demo',
  standalone: true,
  imports: [CommonModule, AdvancedTableComponent, BadgeComponent, ButtonComponent],
  templateUrl: './table-demo.component.html',
  styleUrl: './table-demo.component.css'
})
export class TableDemoComponent implements OnInit {
  @ViewChild('nameTemplate', { static: true }) nameTemplate!: TemplateRef<any>;
  @ViewChild('roleTemplate', { static: true }) roleTemplate!: TemplateRef<any>;
  @ViewChild('statusTemplate', { static: true }) statusTemplate!: TemplateRef<any>;
  @ViewChild('salaryTemplate', { static: true }) salaryTemplate!: TemplateRef<any>;
  @ViewChild('expandedRowTemplate', { static: true }) expandedRowTemplate!: TemplateRef<any>;

  data: User[] = [];
  loading = true;
  allData: User[] = [];
  
  pagination = {
    current: 1,
    pageSize: 10,
    total: 0,
    showSizeChanger: true,
    pageSizeOptions: [10, 20, 50, 100],
    showQuickJumper: true,
    showPagination: true
  };

  sortState: {
    field: string | null;
    direction: 'asc' | 'desc' | null;
  } = {
    field: null,
    direction: null
  };

  columns: TableColumn<User>[] = [];

  constructor(private userDataService: UserDataService) {}

  ngOnInit() {
    this.allData = this.userDataService.generateSampleData();
    this.setupColumns();
    this.loadData();
  }

  private setupColumns() {
    this.columns = [
      {
        key: 'id',
        title: 'ID',
        frozen: true,
        sortable: true,
        width: 80
      },
      {
        key: 'name',
        title: 'Name',
        width: 200,
        sortable: true,
        cellTemplate: this.nameTemplate
      },
      {
        key: 'email',
        title: 'Email',
        width: 250,
        sortable: true
      },
      {
        key: 'role',
        title: 'Role',
        width: 120,
        sortable: true,
        cellTemplate: this.roleTemplate
      },
      {
        key: 'status',
        title: 'Status',
        width: 100,
        sortable: true,
        cellTemplate: this.statusTemplate
      },
      {
        key: 'department',
        title: 'Department',
        width: 150,
        sortable: true
      },
      {
        key: 'joinDate',
        title: 'Join Date',
        width: 120,
        sortable: true
      },
      {
        key: 'salary',
        title: 'Salary',
        width: 120,
        sortable: true,
        cellTemplate: this.salaryTemplate
      },
      {
        key: 'description',
        title: 'Description',
        multiline: false
      },
      {
        key: 'lastLogin',
        title: 'Last Login',
        width: 120,
        sortable: true,
        frozen: 'right'
      }
    ];
  }

  private loadData() {
    this.loading = true;
    
    // Simulate loading delay
    setTimeout(() => {
      let filteredData = [...this.allData];
      
      // Apply sorting
      if (this.sortState.field && this.sortState.direction) {
        filteredData.sort((a, b) => {
          const aVal = a[this.sortState.field as keyof User];
          const bVal = b[this.sortState.field as keyof User];
          
          let comparison = 0;
          if (aVal < bVal) comparison = -1;
          if (aVal > bVal) comparison = 1;
          
          return this.sortState.direction === 'desc' ? -comparison : comparison;
        });
      }

      // Apply pagination
      const startIndex = (this.pagination.current - 1) * this.pagination.pageSize;
      const endIndex = startIndex + this.pagination.pageSize;
      const paginatedData = filteredData.slice(startIndex, endIndex);

      this.data = paginatedData;
      this.pagination.total = filteredData.length;
      this.loading = false;
    }, 500);
  }

  onPageChange(event: { page: number; pageSize: number }) {
    this.pagination.current = event.page;
    this.pagination.pageSize = event.pageSize;
    this.loadData();
  }

  onSort(event: { field: string; direction: 'asc' | 'desc' | null }) {
    this.sortState.field = event.field;
    this.sortState.direction = event.direction;
    this.pagination.current = 1; // Reset to first page
    this.loadData();
  }

  onExpand(event: { expanded: boolean; record: User }) {
    console.log('Row expanded:', event.expanded, event.record);
  }

  editUser(user: User) {
    console.log('Edit user:', user);
  }

  viewProfile(user: User) {
    console.log('View profile:', user);
  }

  deleteUser(user: User) {
    console.log('Delete user:', user);
  }

  getStatusVariant(status: string): 'success' | 'destructive' | 'warning' {
    switch (status) {
      case 'active': return 'success';
      case 'inactive': return 'destructive';
      case 'pending': return 'warning';
      default: return 'warning';
    }
  }

  getRoleVariant(role: string): 'default' | 'secondary' | 'outline' {
    switch (role) {
      case 'Admin': return 'default';
      case 'Manager': return 'secondary';
      default: return 'outline';
    }
  }
}

<div class="min-h-screen bg-background p-6">
  <!-- Header -->
  <div class="flex items-center justify-between mb-8">
    <div class="space-y-2">
      <h1 class="text-3xl font-bold tracking-tight">Advanced Data Table</h1>
      <p class="text-muted-foreground">
        A comprehensive table component with sticky headers, sorting, pagination, expandable rows, frozen columns, and flexible width handling.
      </p>
    </div>
    <button class="inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-9 w-9">
      <!-- Theme toggle placeholder -->
      <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"/>
      </svg>
    </button>
  </div>

  <app-advanced-table
    [data]="data"
    [columns]="columns"
    [loading]="loading"
    [rowKey]="'id'"
    [expandable]="{ expandedRowTemplate: expandedRowTemplate, expandRowByClick: false }"
    [pagination]="pagination"
    [sticky]="{ offsetHeader: 0 }"
    [scroll]="{ x: '100%' }"
    (pageChange)="onPageChange($event)"
    (sort)="onSort($event)"
    (expand)="onExpand($event)"
    class="bg-white rounded-lg shadow">
    
    <!-- Pass the expanded row template -->
    <ng-template #expandedRowTemplate let-record>
      <div class="space-y-4">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div class="space-y-3">
            <h4 class="font-semibold">Contact Information</h4>
            <div class="space-y-2 text-sm">
              <div class="flex justify-between">
                <span class="text-muted-foreground">Email:</span>
                <span>{{ record.email }}</span>
              </div>
              <div class="flex justify-between">
                <span class="text-muted-foreground">Department:</span>
                <span>{{ record.department }}</span>
              </div>
              <div class="flex justify-between">
                <span class="text-muted-foreground">Role:</span>
                <span>{{ record.role }}</span>
              </div>
            </div>
          </div>
          <div class="space-y-3">
            <h4 class="font-semibold">Employment Details</h4>
            <div class="space-y-2 text-sm">
              <div class="flex justify-between">
                <span class="text-muted-foreground">Join Date:</span>
                <span>{{ record.joinDate }}</span>
              </div>
              <div class="flex justify-between">
                <span class="text-muted-foreground">Last Login:</span>
                <span>{{ record.lastLogin }}</span>
              </div>
              <div class="flex justify-between">
                <span class="text-muted-foreground">Salary:</span>
                <span>{{ record.salary | currency:'USD':'symbol':'1.0-0' }}</span>
              </div>
            </div>
          </div>
          <div class="md:col-span-2 space-y-3">
            <h4 class="font-semibold">Description</h4>
            <p class="text-sm text-muted-foreground">{{ record.description }}</p>
          </div>
        </div>
        <div class="flex space-x-2">
          <app-button variant="default" size="sm" (click)="editUser(record)">Edit User</app-button>
          <app-button variant="outline" size="sm" (click)="viewProfile(record)">View Profile</app-button>
          <app-button variant="destructive" size="sm" (click)="deleteUser(record)">Delete User</app-button>
        </div>
      </div>
    </ng-template>
  </app-advanced-table>

  <!-- Feature highlights -->
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mt-8">
    <div class="space-y-2">
      <h3 class="font-semibold">Features Demonstrated</h3>
      <ul class="text-sm text-muted-foreground space-y-1">
        <li>• Sticky header behavior</li>
        <li>• Frozen columns (ID & Last Login)</li>
        <li>• Sortable columns</li>
        <li>• Expandable rows</li>
      </ul>
    </div>
    <div class="space-y-2">
      <h3 class="font-semibold">Pagination</h3>
      <ul class="text-sm text-muted-foreground space-y-1">
        <li>• Configurable page sizes</li>
        <li>• Page navigation</li>
        <li>• Total count display</li>
        <li>• Persistent state</li>
      </ul>
    </div>
    <div class="space-y-2">
      <h3 class="font-semibold">Column Features</h3>
      <ul class="text-sm text-muted-foreground space-y-1">
        <li>• Fixed & flexible widths</li>
        <li>• Text ellipsis handling</li>
        <li>• Custom cell rendering</li>
        <li>• Horizontal scrolling</li>
      </ul>
    </div>
    <div class="space-y-2">
      <h3 class="font-semibold">Event Driven</h3>
      <ul class="text-sm text-muted-foreground space-y-1">
        <li>• Sort events</li>
        <li>• Pagination events</li>
        <li>• Expand events</li>
        <li>• Loading states</li>
      </ul>
    </div>
  </div>

  <!-- Additional content for scroll testing -->
  <div class="mt-16 space-y-6">
    <h2 class="text-2xl font-bold">Additional Content for Scroll Testing</h2>
    <p class="text-muted-foreground">
      Scroll down to see the sticky header behavior in action. The table header should remain visible at the top of the viewport.
    </p>
    
    <div class="space-y-6">
      <div *ngFor="let section of [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]" class="p-6 bg-white rounded-lg shadow">
        <h3 class="font-semibold mb-2">Section {{ section }}</h3>
        <p class="text-muted-foreground mb-4">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor 
          incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 
          exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
        <p class="text-muted-foreground">
          Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu 
          fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in 
          culpa qui officia deserunt mollit anim id est laborum.
        </p>
      </div>
    </div>
  </div>
</div>

<!-- Cell Templates -->
<ng-template #nameTemplate let-value let-record="record">
  <div class="font-medium text-foreground">{{ value }}</div>
</ng-template>

<ng-template #roleTemplate let-value>
  <app-badge [variant]="getRoleVariant(value)">{{ value }}</app-badge>
</ng-template>

<ng-template #statusTemplate let-value>
  <app-badge [variant]="getStatusVariant(value)">{{ value }}</app-badge>
</ng-template>

<ng-template #salaryTemplate let-value>
  {{ value | currency:'USD':'symbol':'1.0-0' }}
</ng-template>
