// angular/src/app/components/advanced-table/advanced-table.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy, ElementRef, ViewChild, TemplateRef, ContentChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TableProps, TableColumn, SortState } from '../../types/table-types';
import { cn } from '../../lib/utils';

@Component({
  selector: 'app-advanced-table',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './advanced-table.component.html',
  styleUrl: './advanced-table.component.css'
})
export class AdvancedTableComponent<T extends Record<string, any>> implements OnInit, OnDestroy {
  @Input() data: T[] = [];
  @Input() columns: TableColumn<T>[] = [];
  @Input() loading: boolean = false;
  @Input() rowKey: string | ((record: T) => string) = 'id';
  @Input() expandable?: TableProps<T>['expandable'];
  @Input() pagination?: TableProps<T>['pagination'];
  @Input() sticky?: TableProps<T>['sticky'];
  @Input() scroll?: TableProps<T>['scroll'];
  @Input() className?: string;

  @Output() pageChange = new EventEmitter<{ page: number; pageSize: number }>();
  @Output() sort = new EventEmitter<{ field: string; direction: 'asc' | 'desc' | null }>();
  @Output() expand = new EventEmitter<{ expanded: boolean; record: T }>();

  @ViewChild('tableContainer', { static: true }) tableContainer!: ElementRef<HTMLDivElement>;
  @ViewChild('tableHeader', { static: true }) tableHeader!: ElementRef<HTMLTableSectionElement>;

  sortState: SortState = { field: null, direction: null };
  expandedRows = new Set<string>();
  stickyTop = 0;
  cn = cn;
  Math = Math;

  trackByRowKey = (index: number, record: T): string => {
    return this.getRowKey(record, index);
  };

  private scrollListener?: () => void;
  private resizeListener?: () => void;

  ngOnInit() {
    this.setupScrollListeners();
    this.updateStickyPosition();
  }

  ngOnDestroy() {
    this.removeScrollListeners();
  }

  private setupScrollListeners() {
    this.scrollListener = () => this.updateStickyPosition();
    this.resizeListener = () => this.updateStickyPosition();

    document.addEventListener('scroll', this.scrollListener, true);
    window.addEventListener('scroll', this.scrollListener);
    window.addEventListener('resize', this.resizeListener);
  }

  private removeScrollListeners() {
    if (this.scrollListener) {
      document.removeEventListener('scroll', this.scrollListener, true);
      window.removeEventListener('scroll', this.scrollListener);
    }
    if (this.resizeListener) {
      window.removeEventListener('resize', this.resizeListener);
    }
  }

  private updateStickyPosition() {
    if (!this.tableContainer) return;

    const rect = this.tableContainer.nativeElement.getBoundingClientRect();
    const newStickyTop = Math.max(0, -rect.top);
    this.stickyTop = newStickyTop;
  }

  getRowKey(record: T, index: number): string {
    if (typeof this.rowKey === 'function') {
      return this.rowKey(record);
    }
    return record[this.rowKey] || index.toString();
  }

  isRowExpanded(record: T, index: number): boolean {
    const key = this.getRowKey(record, index);
    return this.expandedRows.has(key);
  }

  toggleRowExpansion(record: T, index: number) {
    const key = this.getRowKey(record, index);
    const wasExpanded = this.expandedRows.has(key);
    
    if (wasExpanded) {
      this.expandedRows.delete(key);
    } else {
      this.expandedRows.add(key);
    }

    this.expand.emit({ expanded: !wasExpanded, record });
  }

  handleSort(column: TableColumn<T>) {
    if (!column.sortable) return;

    let newDirection: 'asc' | 'desc' | null = 'asc';
    
    if (this.sortState.field === column.key) {
      if (this.sortState.direction === 'asc') {
        newDirection = 'desc';
      } else if (this.sortState.direction === 'desc') {
        newDirection = null;
      }
    }

    this.sortState = { 
      field: newDirection ? column.key : null, 
      direction: newDirection 
    };
    
    this.sort.emit({ field: column.key, direction: newDirection });
  }

  handlePageChange(page: number, pageSize: number) {
    this.pageChange.emit({ page, pageSize });
    this.scrollToTop();
  }

  private scrollToTop() {
    if (this.tableContainer) {
      const tableRect = this.tableContainer.nativeElement.getBoundingClientRect();
      const offsetHeader = this.sticky?.offsetHeader || 0;
      
      if (tableRect.top < offsetHeader) {
        const scrollTop = window.pageYOffset + tableRect.top - offsetHeader;
        
        window.scrollTo({
          top: scrollTop,
          behavior: 'smooth'
        });
      }
    }
  }

  getColumnStyle(column: TableColumn<T>): any {
    const styles: any = {};
    
    if (column.width) {
      styles.width = typeof column.width === 'number' ? `${column.width}px` : column.width;
    }
    if (column.minWidth) {
      styles.minWidth = typeof column.minWidth === 'number' ? `${column.minWidth}px` : column.minWidth;
    }
    if (column.maxWidth) {
      styles.maxWidth = typeof column.maxWidth === 'number' ? `${column.maxWidth}px` : column.maxWidth;
    }

    return styles;
  }

  getCellValue(record: T, column: TableColumn<T>, index: number): any {
    const value = record[column.key];
    if (column.render) {
      return column.render(value, record, index);
    }
    return value;
  }

  getPageNumbers(): number[] {
    if (!this.pagination) return [];
    
    const current = this.pagination.current;
    const total = Math.ceil(this.pagination.total / this.pagination.pageSize);
    const numbers: number[] = [];
    
    // Simple pagination - show first, last, and around current
    const start = Math.max(1, current - 2);
    const end = Math.min(total, current + 2);
    
    for (let i = start; i <= end; i++) {
      numbers.push(i);
    }
    
    return numbers;
  }

  onPageSizeChange(event: Event) {
    const select = event.target as HTMLSelectElement;
    const newPageSize = parseInt(select.value);
    this.handlePageChange(1, newPageSize);
  }
}

<div #tableContainer class="w-full" [ngClass]="className">
  <!-- Loading skeleton -->
  <div *ngIf="loading" class="space-y-2">
    <div class="h-12 bg-gray-200 rounded animate-pulse"></div>
    <div *ngFor="let item of [1,2,3,4,5,6,7,8,9,10]" class="h-16 bg-gray-100 rounded animate-pulse"></div>
  </div>

  <!-- Actual table -->
  <div *ngIf="!loading" class="relative w-full overflow-x-auto">
    <table class="w-full caption-bottom text-sm">
      <!-- Table Header -->
      <thead 
        #tableHeader
        class="[&_tr]:border-b"
        [style.position]="sticky ? 'sticky' : 'static'"
        [style.top]="sticky ? stickyTop + 'px' : 'auto'"
        [style.z-index]="sticky ? '10' : 'auto'">
        <tr class="border-b transition-colors hover:bg-muted/50">
          <!-- Expand column -->
          <th *ngIf="expandable" 
              class="h-10 px-2 text-left align-middle font-medium whitespace-nowrap">
            <div class="text-foreground">Expand</div>
          </th>

          <!-- Data columns -->
          <th *ngFor="let column of columns" 
              [ngStyle]="getColumnStyle(column)"
              [ngClass]="{
                'cursor-pointer': column.sortable,
                'text-foreground h-10 px-2 text-left align-middle font-medium whitespace-nowrap': true
              }"
              (click)="handleSort(column)">
            <div class="flex items-center space-x-1">
              <div class="text-foreground">{{ column.title }}</div>
              <div *ngIf="column.sortable" class="flex flex-col">
                <svg 
                  class="w-3 h-3"
                  [ngClass]="{
                    'text-gray-400': sortState.field !== column.key || sortState.direction !== 'asc',
                    'text-blue-600': sortState.field === column.key && sortState.direction === 'asc'
                  }"
                  fill="currentColor" 
                  viewBox="0 0 20 20">
                  <path d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"/>
                </svg>
                <svg 
                  class="w-3 h-3 -mt-1"
                  [ngClass]="{
                    'text-gray-400': sortState.field !== column.key || sortState.direction !== 'desc',
                    'text-blue-600': sortState.field === column.key && sortState.direction === 'desc'
                  }"
                  fill="currentColor" 
                  viewBox="0 0 20 20">
                  <path d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"/>
                </svg>
              </div>
            </div>
          </th>
        </tr>
      </thead>

      <!-- Table Body -->
      <tbody class="[&_tr:last-child]:border-0">
        <ng-container *ngFor="let record of data; let i = index; trackBy: trackByRowKey">
          <!-- Main row -->
          <tr class="border-b transition-colors hover:bg-muted/50">
            <!-- Expand button cell -->
            <td *ngIf="expandable" class="px-2 py-3">
              <button 
                class="inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 hover:bg-accent hover:text-accent-foreground h-8 w-8"
                [ngClass]="{
                  'bg-accent text-accent-foreground': isRowExpanded(record, i)
                }"
                (click)="toggleRowExpansion(record, i)">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path *ngIf="!isRowExpanded(record, i)" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/>
                  <path *ngIf="isRowExpanded(record, i)" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 12H6"/>
                </svg>
              </button>
            </td>

            <!-- Data cells -->
            <td *ngFor="let column of columns" 
                [ngStyle]="getColumnStyle(column)"
                class="px-2 py-3">
              <ng-container *ngIf="column.cellTemplate; else defaultCell">
                <ng-container 
                  *ngTemplateOutlet="column.cellTemplate; context: { 
                    $implicit: getCellValue(record, column, i), 
                    record: record, 
                    index: i 
                  }">
                </ng-container>
              </ng-container>
              <ng-template #defaultCell>
                {{ getCellValue(record, column, i) }}
              </ng-template>
            </td>
          </tr>

          <!-- Expanded row -->
          <tr *ngIf="isRowExpanded(record, i)" class="border-b">
            <td [attr.colspan]="columns.length + (expandable ? 1 : 0)" class="px-2 py-4">
              <ng-container *ngIf="expandable?.expandedRowTemplate; else defaultExpanded">
                <ng-container 
                  *ngTemplateOutlet="expandable.expandedRowTemplate; context: { 
                    $implicit: record, 
                    index: i 
                  }">
                </ng-container>
              </ng-container>
              <ng-template #defaultExpanded>
                <div class="p-4 bg-gray-50 rounded">
                  <pre>{{ record | json }}</pre>
                </div>
              </ng-template>
            </td>
          </tr>
        </ng-container>
      </tbody>
    </table>
  </div>

  <!-- Pagination -->
  <div *ngIf="pagination && pagination.showPagination !== false" 
       class="flex items-center justify-between px-2 py-4">
    <div class="flex items-center space-x-6 lg:space-x-8">
      <div class="text-sm text-muted-foreground">
        Showing {{ (pagination.current - 1) * pagination.pageSize + 1 }} to 
        {{ Math.min(pagination.current * pagination.pageSize, pagination.total) }} of 
        {{ pagination.total }} results
      </div>
      <div *ngIf="pagination.showSizeChanger" class="flex items-center space-x-2">
        <div class="text-sm font-medium">Show</div>
        <select 
          class="border border-input bg-background px-3 py-1 text-sm ring-offset-background focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
          [value]="pagination.pageSize"
          (change)="onPageSizeChange($event)">
          <option *ngFor="let size of pagination.pageSizeOptions || [10, 20, 50, 100]" 
                  [value]="size">{{ size }}</option>
        </select>
      </div>
    </div>
    <div class="flex items-center space-x-2">
      <button 
        class="inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-8 w-8"
        [disabled]="pagination.current <= 1"
        (click)="handlePageChange(pagination.current - 1, pagination.pageSize)">
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/>
        </svg>
      </button>
      
      <div class="text-sm font-medium">
        Page {{ pagination.current }} of {{ Math.ceil(pagination.total / pagination.pageSize) }}
      </div>
      
      <button 
        class="inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-8 w-8"
        [disabled]="pagination.current >= Math.ceil(pagination.total / pagination.pageSize)"
        (click)="handlePageChange(pagination.current + 1, pagination.pageSize)">
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
        </svg>
      </button>
    </div>
  </div>
</div>

// src/components/AdvancedTable.tsx
import React, { useState, useRef, useEffect } from 'react';
import { cn } from '@/lib/utils';
import { TableProps, TableColumn, SortState } from '@/lib/table-types';
import { CaretDown, CaretUp, CaretLeft, CaretRight, Plus, Minus } from '@phosphor-icons/react';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Skeleton } from '@/components/ui/skeleton';
import { Card } from '@/components/ui/card';

export function AdvancedTable<T extends Record<string, any>>({
  data,
  columns,
  loading = false,
  rowKey = 'id',
  expandable,
  pagination,
  sticky,
  scroll,
  onPageChange,
  onSort,
  onExpand,
  className
}: TableProps<T>) {
  const [sortState, setSortState] = useState<SortState>({ field: null, direction: null });
  const [expandedRows, setExpandedRows] = useState<Set<string>>(new Set());
  const [stickyTop, setStickyTop] = useState(0);
  const tableRef = useRef<HTMLDivElement>(null);
  const headerRef = useRef<HTMLTableSectionElement>(null);

  // Calculate sticky position based on scroll
  useEffect(() => {
    const updateStickyPosition = () => {
      if (!tableRef.current) return;
      
      const rect = tableRef.current.getBoundingClientRect();
      const newStickyTop = Math.max(0, -rect.top);
      setStickyTop(newStickyTop);
    };

    const handleScroll = () => {
      updateStickyPosition();
    };

    // Listen to both window scroll and any parent scroll containers
    document.addEventListener('scroll', handleScroll, true);
    window.addEventListener('scroll', handleScroll);
    window.addEventListener('resize', updateStickyPosition);

    // Initial calculation
    updateStickyPosition();

    return () => {
      document.removeEventListener('scroll', handleScroll, true);
      window.removeEventListener('scroll', handleScroll);
      window.removeEventListener('resize', updateStickyPosition);
    };
  }, []);

  // Recalculate sticky position when data changes (e.g., pagination)
  useEffect(() => {
    const updateStickyPosition = () => {
      if (!tableRef.current) return;
      
      const rect = tableRef.current.getBoundingClientRect();
      const newStickyTop = Math.max(0, -rect.top);
      setStickyTop(newStickyTop);
    };

    // Use setTimeout to ensure DOM has updated after data change
    const timer = setTimeout(updateStickyPosition, 0);
    
    return () => clearTimeout(timer);
  }, [data, pagination?.current]);

  const leftFrozenColumns = columns.filter(col => col.frozen === true || col.frozen === 'left');
  const rightFrozenColumns = columns.filter(col => col.frozen === 'right');
  const scrollableColumns = columns.filter(col => !col.frozen);

  const getRowKey = (record: T, index: number): string => {
    return typeof rowKey === 'function' ? rowKey(record) : String(record[rowKey] || index);
  };

  const scrollToTop = () => {
    if (tableRef.current) {
      const tableRect = tableRef.current.getBoundingClientRect();
      const offsetHeader = sticky?.offsetHeader || 0;
      
      // Only scroll if the table top is not visible or if we're scrolled past it
      // Check if table top is above the viewport (considering any offset header)
      if (tableRect.top < offsetHeader) {
        const scrollTop = window.pageYOffset + tableRect.top - offsetHeader;
        
        window.scrollTo({
          top: scrollTop,
          behavior: 'smooth'
        });
      }
      // If table is already visible at the top, don't scroll
    }
  };

  const handlePageChangeWithScroll = (page: number, pageSize: number) => {
    onPageChange?.(page, pageSize);
    scrollToTop();
  };

  const handleSort = (column: TableColumn<T>) => {
    if (!column.sortable) return;

    let newDirection: 'asc' | 'desc' | null = 'asc';
    
    if (sortState.field === column.key) {
      if (sortState.direction === 'asc') {
        newDirection = 'desc';
      } else if (sortState.direction === 'desc') {
        newDirection = null;
      }
    }

    setSortState({ field: newDirection ? column.key : null, direction: newDirection });
    onSort?.(column.key, newDirection);
  };

  const handleExpand = (record: T) => {
    const key = getRowKey(record, 0);
    const newExpandedRows = new Set(expandedRows);
    
    if (newExpandedRows.has(key)) {
      newExpandedRows.delete(key);
      onExpand?.(false, record);
    } else {
      newExpandedRows.add(key);
      onExpand?.(true, record);
    }
    
    setExpandedRows(newExpandedRows);
  };

  const renderColumnHeader = (column: TableColumn<T>) => {
    const isLeftFrozen = column.frozen === true || column.frozen === 'left';
    const isRightFrozen = column.frozen === 'right';
    const isLastLeftFrozen = isLeftFrozen && leftFrozenColumns[leftFrozenColumns.length - 1]?.key === column.key;
    const isFirstRightFrozen = isRightFrozen && rightFrozenColumns[0]?.key === column.key;
    
    // Calculate left offset for left frozen columns
    let leftOffset = 0;
    if (isLeftFrozen) {
      if (expandable) leftOffset += 48; // Expand button width
      
      // Add widths of previous left frozen columns
      for (const leftCol of leftFrozenColumns) {
        if (leftCol.key === column.key) break;
        const width = leftCol.width;
        leftOffset += typeof width === 'number' ? width : parseInt(String(width) || '100');
      }
    }
    
    return (
      <th
        key={column.key}
        className={cn(
          "px-4 py-3 text-left text-sm font-medium text-foreground bg-card/95 backdrop-blur-sm border-b border-border relative",
          isLeftFrozen && "sticky z-50",
          isRightFrozen && "sticky right-0 z-40",
          column.sortable && "cursor-pointer hover:bg-muted/50 transition-colors",
          // Add visual distinction for frozen columns
          isLastLeftFrozen && "border-r-2 border-border shadow-lg shadow-black/5",
          isFirstRightFrozen && "border-l-2 border-border shadow-lg shadow-black/5"
        )}
        style={{
          width: column.width,
          minWidth: column.minWidth,
          maxWidth: column.maxWidth,
          ...(isLeftFrozen && { left: leftOffset }),
          ...(isLeftFrozen && { top: `${stickyTop}px` }),
          ...(isRightFrozen && { top: `${stickyTop}px` }),
        }}
        onClick={() => handleSort(column)}
      >
        <div className="flex items-center gap-2">
          <span className={cn(column.ellipsis && "truncate")}>{column.title}</span>
          {column.sortable && (
            <div className="flex flex-col">
              {sortState.field === column.key ? (
                sortState.direction === 'asc' ? (
                  <CaretUp size={14} className="text-primary" />
                ) : sortState.direction === 'desc' ? (
                  <CaretDown size={14} className="text-primary" />
                ) : (
                  <div className="flex flex-col">
                    <CaretUp size={12} className="text-muted-foreground" />
                    <CaretDown size={12} className="text-muted-foreground -mt-1" />
                  </div>
                )
              ) : (
                <div className="flex flex-col">
                  <CaretUp size={12} className="text-muted-foreground" />
                  <CaretDown size={12} className="text-muted-foreground -mt-1" />
                </div>
              )}
            </div>
          )}
        </div>
      </th>
    );
  };

  const renderCell = (column: TableColumn<T>, record: T, index: number) => {
    const value = record[column.key];
    const content = column.render ? column.render(value, record, index) : value;
    const isLeftFrozen = column.frozen === true || column.frozen === 'left';
    const isRightFrozen = column.frozen === 'right';
    const isLastLeftFrozen = isLeftFrozen && leftFrozenColumns[leftFrozenColumns.length - 1]?.key === column.key;
    const isFirstRightFrozen = isRightFrozen && rightFrozenColumns[0]?.key === column.key;
    
    // Calculate left offset for left frozen columns
    let leftOffset = 0;
    if (isLeftFrozen) {
      if (expandable) leftOffset += 48; // Expand button width
      
      // Add widths of previous left frozen columns
      for (const leftCol of leftFrozenColumns) {
        if (leftCol.key === column.key) break;
        const width = leftCol.width;
        leftOffset += typeof width === 'number' ? width : parseInt(String(width) || '100');
      }
    }
    
    return (
      <td
        key={column.key}
        className={cn(
          "px-4 py-3 text-sm relative transition-colors",
          isLeftFrozen && "sticky z-30 bg-card/95 backdrop-blur-sm frozen-cell",
          isRightFrozen && "sticky right-0 z-20 bg-card/95 backdrop-blur-sm frozen-cell",
          column.ellipsis && "max-w-0",
          column.multiline ? "whitespace-normal" : "whitespace-nowrap",
          // Add visual distinction for frozen columns
          isLastLeftFrozen && "border-r-2 border-border shadow-lg shadow-black/5",
          isFirstRightFrozen && "border-l-2 border-border shadow-lg shadow-black/5"
        )}
        style={{
          width: column.width,
          minWidth: column.minWidth,
          maxWidth: column.maxWidth,
          ...(isLeftFrozen && { left: leftOffset }),
        }}
      >
        {column.ellipsis ? (
          <div className="truncate" title={String(value)}>
            {content}
          </div>
        ) : (
          content
        )}
      </td>
    );
  };

  const renderExpandButton = (record: T, index: number) => {
    const key = getRowKey(record, index);
    const isExpanded = expandedRows.has(key);

    return (
      <td className="px-4 py-3 sticky left-0 z-30 bg-card/95 backdrop-blur-sm w-12 border-r-2 shadow-lg shadow-black/5 relative frozen-cell transition-colors">
        {expandable?.expandRowByClick ? (
          // Just show an indicator when row click expands
          <div className="flex items-center justify-center h-6 w-6">
            {isExpanded ? <Minus size={14} className="text-muted-foreground" /> : <Plus size={14} className="text-muted-foreground" />}
          </div>
        ) : (
          // Show clickable button when manual expand
          <Button
            variant="ghost"
            size="sm"
            onClick={() => handleExpand(record)}
            className="h-6 w-6 p-0"
          >
            {isExpanded ? <Minus size={14} /> : <Plus size={14} />}
          </Button>
        )}
      </td>
    );
  };

  const renderPagination = () => {
    if (!pagination || !pagination.showPagination) return null;

    const { current, pageSize, total, showSizeChanger, pageSizeOptions = [10, 20, 50, 100] } = pagination;
    const totalPages = Math.ceil(total / pageSize);
    const startItem = (current - 1) * pageSize + 1;
    const endItem = Math.min(current * pageSize, total);

    return (
      <div className="flex items-center justify-between px-4 py-3 border-t border-border bg-card">
        <div className="flex items-center gap-4">
          <span className="text-sm text-muted-foreground">
            Showing {startItem} to {endItem} of {total} results
          </span>
          {showSizeChanger && (
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground">Show</span>
              <Select
                value={pageSize.toString()}
                onValueChange={(value) => handlePageChangeWithScroll(1, parseInt(value))}
              >
                <SelectTrigger className="w-20">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {pageSizeOptions.map(size => (
                    <SelectItem key={size} value={size.toString()}>
                      {size}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}
        </div>
        
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => handlePageChangeWithScroll(current - 1, pageSize)}
            disabled={current <= 1}
          >
            <CaretLeft size={16} />
          </Button>
          
          <span className="text-sm text-muted-foreground">
            Page {current} of {totalPages}
          </span>
          
          <Button
            variant="outline"
            size="sm"
            onClick={() => handlePageChangeWithScroll(current + 1, pageSize)}
            disabled={current >= totalPages}
          >
            <CaretRight size={16} />
          </Button>
        </div>
      </div>
    );
  };

  if (loading) {
    return (
      <Card className={cn("overflow-hidden", className)}>
        <div className="p-4">
          <Skeleton className="h-8 w-full mb-4" />
          {Array.from({ length: 5 }).map((_, i) => (
            <Skeleton key={i} className="h-12 w-full mb-2" />
          ))}
        </div>
      </Card>
    );
  }

  return (
    <div className={cn("flex flex-col", className)}>
      <Card className="flex flex-col">
        <div
          ref={tableRef}
          className="overflow-x-auto flex-1"
        >
          <table className="w-full table-fixed border-collapse" style={{ minWidth: scroll?.x }}>
            {/* First thead for layout spacing - invisible */}
            <thead className="invisible">
              <tr>
                {expandable && (
                  <th className="w-12 px-4 py-3" />
                )}
                {leftFrozenColumns.map(column => (
                  <th
                    key={`layout-${column.key}`}
                    style={{
                      width: column.width,
                      minWidth: column.minWidth,
                      maxWidth: column.maxWidth
                    }}
                    className="px-4 py-3"
                  >
                    {column.title}
                  </th>
                ))}
                {scrollableColumns.map(column => (
                  <th
                    key={`layout-${column.key}`}
                    style={{
                      width: column.width,
                      minWidth: column.minWidth,
                      maxWidth: column.maxWidth
                    }}
                    className="px-4 py-3"
                  >
                    {column.title}
                  </th>
                ))}
                {rightFrozenColumns.map(column => (
                  <th
                    key={`layout-${column.key}`}
                    style={{
                      width: column.width,
                      minWidth: column.minWidth,
                      maxWidth: column.maxWidth
                    }}
                    className="px-4 py-3"
                  >
                    {column.title}
                  </th>
                ))}
              </tr>
            </thead>
            
            {/* Second thead for visible sticky header */}
            <thead 
              ref={headerRef}
              className="sticky z-40 bg-card/95 backdrop-blur-sm border-b border-border"
              style={{ top: `${stickyTop}px` }}
            >
              <tr>
                {expandable && (
                  <th 
                    className="w-12 px-4 py-3 sticky left-0 z-50 bg-card/95 backdrop-blur-sm border-b border-border border-r-2 shadow-lg shadow-black/5 relative"
                    style={{ top: `${stickyTop}px` }}
                  >
                    <span className="sr-only">Expand</span>
                  </th>
                )}
                {leftFrozenColumns.map(renderColumnHeader)}
                {scrollableColumns.map(renderColumnHeader)}
                {rightFrozenColumns.map(renderColumnHeader)}
              </tr>
            </thead>
            
            <tbody>
              {data.length === 0 ? (
                <tr>
                  <td
                    colSpan={columns.length + (expandable ? 1 : 0)}
                    className="px-4 py-8 text-center text-muted-foreground"
                  >
                    No data available
                  </td>
                </tr>
              ) : (
                data.map((record, index) => {
                  const key = getRowKey(record, index);
                  const isExpanded = expandedRows.has(key);
                  
                  return (
                    <React.Fragment key={key}>
                      <tr
                        className={cn(
                          "table-row hover:bg-muted/50 transition-colors",
                          expandable?.expandRowByClick && "cursor-pointer"
                        )}
                        onClick={() => expandable?.expandRowByClick && handleExpand(record)}
                      >
                        {expandable && renderExpandButton(record, index)}
                        {leftFrozenColumns.map(column => renderCell(column, record, index))}
                        {scrollableColumns.map(column => renderCell(column, record, index))}
                        {rightFrozenColumns.map(column => renderCell(column, record, index))}
                      </tr>
                      {expandable && isExpanded && (
                        <tr className="bg-muted/20">
                          <td colSpan={columns.length + 1} className="p-0">
                            <div className="sticky left-0 right-0 z-10 p-4 bg-muted/20 border-b border-border">
                              {expandable.expandedRowRender(record, index)}
                            </div>
                          </td>
                        </tr>
                      )}
                    </React.Fragment>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
        {renderPagination()}
      </Card>
    </div>
  );
}
